print("\n\nWelcome to the Mad Lib Generator !" + "\n" + "\n")

adjective1 = raw_input("Type in an adjective : ")
adjective2 = raw_input("Another adjective : ")
adjective3 = raw_input("Add another adjective : ")
adjective4 = raw_input("One more adjective : ")
animals = raw_input("Plural animal (e.g. puppies) : ")
verb = raw_input("Now a verb: ")
noun = raw_input("Now a plural noun : ")
first_name = raw_input("The first name of the women musician : ")
beverage = raw_input("A beverage : ")
body_parts = raw_input("And finally, a plural body part : ")
print("\n \n")
print("Excellent choices! Here's your story")
print("\n---------------------------------\n")
print("\nThere once was a " + adjective1 + " programmer named " + first_name + " \nwho wanted to build a " + adjective2 + " mobile app to \nhelp " + adjective3 +" " +  animals + " to find new homes.")
print("\n" + first_name + " stayed up all night , drinking lots of \ncaffeinated " + beverage + " as she worked and worked \ntrying to complete her "+ adjective4 + " program. ")
print("\nWhenever " + first_name + " hit a dead end , she would \nexclaim " + " *"+ noun  + "*!")
print("\nBut she was not discouraged, and after a quick break \nto " + verb + " and clear her head , she got back to work. ")
print("\nBy morning, when the sun started to rise , she let out a \nbig yawn and streched her " + body_parts + ".\n" + "Finally , she was done.")
print("\n-----------------------------------\n")
